In [1]:
import numpy as np
import pandas as pd

#### Numpy Version

In [2]:
np.__version__

'1.20.3'

#### Pandas Version

In [3]:
pd.__version__

'1.3.2'

#### Read CSV File

In [4]:
df = pd.read_csv('data.csv')
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

#### Question 3
What's the average price of BMW cars in the dataset?

In [5]:
average_price_BMW = df[df['Make'] == 'BMW']['MSRP'].mean()
average_price_BMW

61546.76347305389

#### Question 4

Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [6]:
null_Engine_HP = df[df['Year'] >= 2015]['Engine HP'].isnull().sum()
null_Engine_HP

51

#### Question 5
    Calculate the average "Engine HP" in the dataset.
    Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
    Now, calcualte the average of "Engine HP" again.
    Has it changed?


In [7]:
Engine_HP_mean = df['Engine HP'].mean()
print(round(Engine_HP_mean))

249


In [8]:
df_Copy = df.copy()

In [9]:
df_Copy['Engine HP'] = df_Copy['Engine HP'].fillna(Engine_HP_mean)

In [10]:
print(round(df_Copy['Engine HP'].mean()))

249


No it doesn't change.

Question 6

    Select all the "Rolls-Royce" cars from the dataset.
    Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
    Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
    Get the underlying NumPy array. Let's call it X.
    Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
    Invert XTX.
    What's the sum of all the elements of the result?


In [11]:
rolsRoys = df[df['Make'] == "Rolls-Royce"]

In [12]:
rolsRoys = rolsRoys[["Engine HP", "Engine Cylinders", "highway MPG"]]


In [13]:
rolsRoys.drop_duplicates(inplace = True)
rolsRoys.shape

(7, 3)

In [14]:
x = np.array(rolsRoys)

In [15]:
xtx = x.T

In [16]:
mult = xtx.dot(x)
mult

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [17]:
multinv = np.linalg.inv(mult)
multinv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [18]:
multinv.sum()

0.032212320677486195

Questions 7

    Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].
    Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
    What's the value of the first element of w?.


In [19]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [20]:
mult = multinv.dot(x.T)

In [21]:
mult.dot(y)

array([ 0.19989598, 31.02612262, 31.65378877])